head_node_type:
  name: head
  instance_type: n2-standard-8
  resources:
    cpu: 0
# TODO - switch to true when slim image is used
auto_select_worker_config: false
worker_node_types:
- name: 1xT4:8CPU-30GB
  instance_type: n1-standard-8-nvidia-t4-16gb-1
  min_workers: 1
  max_workers: 1
flags:
  allow-cross-zone-autoscaling: false
