name: "stable-diffusion-service"
ray_serve_config:
  applications:
    - name: stable-diffusion
      import_path: main:stable_diffusion_app
      runtime_env:
        working_dir: "."
        pip:
          - diffusers==0.25.0
          - transformers==4.36.2
          - accelerate==0.25.0
